security:
    password_hashers:
        Blog\User\Domain\Entity\Admin:
            algorithm: auto

    providers:
        admin_provider:
            entity:
                class: Blog\User\Domain\Entity\Admin
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: admin_provider

            form_login:
                login_path: app_login
                check_path: app_login
                username_parameter: email
                password_parameter: password
                enable_csrf: true
                default_target_path: sonata_admin_dashboard

            logout:
                path: /logout
                target: app_login

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
